arm_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Revolute_12
    - Revolute_13
    - Revolute_14
    - Revolute_15
    - Revolute_16
    - Revolute_17
  gains:
    Revolute_12:
      p: 350
      d: 100
      i: 1
      i_clamp: 1
    Revolute_13:
      p: 350
      d: 100
      i: 1
      i_clamp: 1
    Revolute_14:
      p: 350
      d: 100
      i: 1
      i_clamp: 1
    Revolute_15:
      p: 350
      d: 100
      i: 1
      i_clamp: 1
    Revolute_16:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Revolute_17:
      p: 100
      d: 1
      i: 1
      i_clamp: 1